# Changes here will be overwritten by Copier
_commit: d860a14
_src_path: https://github.com/dalito/linkml-project-copier
add_example: true
copyright_year: '2025'
email: jhc@lbl.gov
full_name: Harry Caufield
gh_action_docs_preview: false
gh_action_pypi: false
github_org: caufieldjh
license: BSD-3-Clause
project_description: Sociome Knowledge Graph
project_name: kg-sociome
project_slug: kg_sociome

